# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import servicio_pb2 as servicio__pb2


class ReservationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReservation = channel.unary_unary(
                '/pb.ReservationService/GetReservation',
                request_serializer=servicio__pb2.GetReservationRequest.SerializeToString,
                response_deserializer=servicio__pb2.GetReservationResponse.FromString,
                )
        self.ListReservations = channel.unary_unary(
                '/pb.ReservationService/ListReservations',
                request_serializer=servicio__pb2.ListReservationsRequest.SerializeToString,
                response_deserializer=servicio__pb2.ListReservationsResponse.FromString,
                )
        self.CreateReservation = channel.unary_unary(
                '/pb.ReservationService/CreateReservation',
                request_serializer=servicio__pb2.CreateReservationRequest.SerializeToString,
                response_deserializer=servicio__pb2.CreateReservationResponse.FromString,
                )


class ReservationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReservations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservation,
                    request_deserializer=servicio__pb2.GetReservationRequest.FromString,
                    response_serializer=servicio__pb2.GetReservationResponse.SerializeToString,
            ),
            'ListReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReservations,
                    request_deserializer=servicio__pb2.ListReservationsRequest.FromString,
                    response_serializer=servicio__pb2.ListReservationsResponse.SerializeToString,
            ),
            'CreateReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReservation,
                    request_deserializer=servicio__pb2.CreateReservationRequest.FromString,
                    response_serializer=servicio__pb2.CreateReservationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReservationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ReservationService/GetReservation',
            servicio__pb2.GetReservationRequest.SerializeToString,
            servicio__pb2.GetReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ReservationService/ListReservations',
            servicio__pb2.ListReservationsRequest.SerializeToString,
            servicio__pb2.ListReservationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ReservationService/CreateReservation',
            servicio__pb2.CreateReservationRequest.SerializeToString,
            servicio__pb2.CreateReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/pb.UserService/GetUser',
                request_serializer=servicio__pb2.GetUserRequest.SerializeToString,
                response_deserializer=servicio__pb2.UserResponse.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/pb.UserService/CreateUser',
                request_serializer=servicio__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=servicio__pb2.UserResponse.FromString,
                )
        self.AuthenticateUser = channel.unary_unary(
                '/pb.UserService/AuthenticateUser',
                request_serializer=servicio__pb2.AuthenticateUserRequest.SerializeToString,
                response_deserializer=servicio__pb2.AuthenticateUserResponse.FromString,
                )
        self.LogoutUser = channel.unary_unary(
                '/pb.UserService/LogoutUser',
                request_serializer=servicio__pb2.LogoutRequest.SerializeToString,
                response_deserializer=servicio__pb2.SessionResponse.FromString,
                )
        self.ValidateToken = channel.unary_unary(
                '/pb.UserService/ValidateToken',
                request_serializer=servicio__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=servicio__pb2.SessionResponse.FromString,
                )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=servicio__pb2.GetUserRequest.FromString,
                    response_serializer=servicio__pb2.UserResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=servicio__pb2.CreateUserRequest.FromString,
                    response_serializer=servicio__pb2.UserResponse.SerializeToString,
            ),
            'AuthenticateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateUser,
                    request_deserializer=servicio__pb2.AuthenticateUserRequest.FromString,
                    response_serializer=servicio__pb2.AuthenticateUserResponse.SerializeToString,
            ),
            'LogoutUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutUser,
                    request_deserializer=servicio__pb2.LogoutRequest.FromString,
                    response_serializer=servicio__pb2.SessionResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=servicio__pb2.ValidateTokenRequest.FromString,
                    response_serializer=servicio__pb2.SessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.UserService/GetUser',
            servicio__pb2.GetUserRequest.SerializeToString,
            servicio__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.UserService/CreateUser',
            servicio__pb2.CreateUserRequest.SerializeToString,
            servicio__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AuthenticateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.UserService/AuthenticateUser',
            servicio__pb2.AuthenticateUserRequest.SerializeToString,
            servicio__pb2.AuthenticateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogoutUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.UserService/LogoutUser',
            servicio__pb2.LogoutRequest.SerializeToString,
            servicio__pb2.SessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.UserService/ValidateToken',
            servicio__pb2.ValidateTokenRequest.SerializeToString,
            servicio__pb2.SessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchAvailableRooms = channel.unary_unary(
                '/pb.InventoryService/SearchAvailableRooms',
                request_serializer=servicio__pb2.SearchRequest.SerializeToString,
                response_deserializer=servicio__pb2.SearchResponse.FromString,
                )
        self.UpdateStock = channel.unary_unary(
                '/pb.InventoryService/UpdateStock',
                request_serializer=servicio__pb2.UpdateStockRequest.SerializeToString,
                response_deserializer=servicio__pb2.UpdateStockResponse.FromString,
                )


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchAvailableRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchAvailableRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchAvailableRooms,
                    request_deserializer=servicio__pb2.SearchRequest.FromString,
                    response_serializer=servicio__pb2.SearchResponse.SerializeToString,
            ),
            'UpdateStock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStock,
                    request_deserializer=servicio__pb2.UpdateStockRequest.FromString,
                    response_serializer=servicio__pb2.UpdateStockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchAvailableRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.InventoryService/SearchAvailableRooms',
            servicio__pb2.SearchRequest.SerializeToString,
            servicio__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.InventoryService/UpdateStock',
            servicio__pb2.UpdateStockRequest.SerializeToString,
            servicio__pb2.UpdateStockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class NotificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendConfirmation = channel.unary_unary(
                '/pb.NotificationService/SendConfirmation',
                request_serializer=servicio__pb2.SendConfirmationRequest.SerializeToString,
                response_deserializer=servicio__pb2.SendConfirmationResponse.FromString,
                )


class NotificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendConfirmation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendConfirmation': grpc.unary_unary_rpc_method_handler(
                    servicer.SendConfirmation,
                    request_deserializer=servicio__pb2.SendConfirmationRequest.FromString,
                    response_serializer=servicio__pb2.SendConfirmationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendConfirmation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.NotificationService/SendConfirmation',
            servicio__pb2.SendConfirmationRequest.SerializeToString,
            servicio__pb2.SendConfirmationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
