FROM nginx:alpine

# Copiar los archivos estáticos al directorio de Nginx
COPY . /usr/share/nginx/html/

# Exponer el puerto 80 (Nginx por defecto)
EXPOSE 80

# El comando por defecto de nginx:alpine ya inicia el servidor
