{
 "title": "Origen X - Observabilidad 3 Pilares",
 "tags": [
  "observabilidad",
  "3-pilares"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pilar 1 - Metricas Prometheus por servicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(scrape_samples_scraped[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pilar 2 - Logs centralizados Loki",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=~\"api_gateway|user-service|reservation_service|inventario_service|notification_service\"}"
    }
   ]
  },
  {
   "title": "Pilar 3 - Trazas distribuidas Tempo - flujo aplicacion",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "{ resource.service.name =~ \"api-gateway|reservation-service|inventory-service|notification-service\" }"
    }
   ]
  }
 ]
}