# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notifications.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\rnotifications\"P\n\x17SendConfirmationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x0c\n\x04tipo\x18\x03 \x01(\t\"+\n\x18SendConfirmationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32z\n\x13NotificationService\x12\x63\n\x10SendConfirmation\x12&.notifications.SendConfirmationRequest\x1a\'.notifications.SendConfirmationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDCONFIRMATIONREQUEST']._serialized_start=38
  _globals['_SENDCONFIRMATIONREQUEST']._serialized_end=118
  _globals['_SENDCONFIRMATIONRESPONSE']._serialized_start=120
  _globals['_SENDCONFIRMATIONRESPONSE']._serialized_end=163
  _globals['_NOTIFICATIONSERVICE']._serialized_start=165
  _globals['_NOTIFICATIONSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
