"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Reservation(_message.Message):
    """─ Mensajes Reservas ─────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    RESERVATION_ID_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    HOTEL_ID_FIELD_NUMBER: _builtins.int
    ROOM_TYPE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    FECHA_INICIO_FIELD_NUMBER: _builtins.int
    FECHA_FIN_FIELD_NUMBER: _builtins.int
    MONTO_TOTAL_FIELD_NUMBER: _builtins.int
    reservation_id: _builtins.str
    user_id: _builtins.str
    hotel_id: _builtins.str
    room_type_id: _builtins.str
    status: _builtins.str
    fecha_inicio: _builtins.str
    fecha_fin: _builtins.str
    monto_total: _builtins.float
    def __init__(
        self,
        *,
        reservation_id: _builtins.str = ...,
        user_id: _builtins.str = ...,
        hotel_id: _builtins.str = ...,
        room_type_id: _builtins.str = ...,
        status: _builtins.str = ...,
        fecha_inicio: _builtins.str = ...,
        fecha_fin: _builtins.str = ...,
        monto_total: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fecha_fin", b"fecha_fin", "fecha_inicio", b"fecha_inicio", "hotel_id", b"hotel_id", "monto_total", b"monto_total", "reservation_id", b"reservation_id", "room_type_id", b"room_type_id", "status", b"status", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Reservation: _TypeAlias = Reservation  # noqa: Y015

@_typing.final
class GetReservationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESERVATION_ID_FIELD_NUMBER: _builtins.int
    reservation_id: _builtins.str
    def __init__(
        self,
        *,
        reservation_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reservation_id", b"reservation_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetReservationRequest: _TypeAlias = GetReservationRequest  # noqa: Y015

@_typing.final
class GetReservationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESERVATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def reservation(self) -> Global___Reservation: ...
    def __init__(
        self,
        *,
        reservation: Global___Reservation | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["reservation", b"reservation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reservation", b"reservation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetReservationResponse: _TypeAlias = GetReservationResponse  # noqa: Y015

@_typing.final
class ListReservationsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListReservationsRequest: _TypeAlias = ListReservationsRequest  # noqa: Y015

@_typing.final
class ListReservationsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESERVATIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def reservations(self) -> _containers.RepeatedCompositeFieldContainer[Global___Reservation]: ...
    def __init__(
        self,
        *,
        reservations: _abc.Iterable[Global___Reservation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reservations", b"reservations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListReservationsResponse: _TypeAlias = ListReservationsResponse  # noqa: Y015

@_typing.final
class CreateReservationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    HOTEL_ID_FIELD_NUMBER: _builtins.int
    ROOM_TYPE_ID_FIELD_NUMBER: _builtins.int
    FECHA_INICIO_FIELD_NUMBER: _builtins.int
    FECHA_FIN_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    hotel_id: _builtins.str
    room_type_id: _builtins.str
    fecha_inicio: _builtins.str
    fecha_fin: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        hotel_id: _builtins.str = ...,
        room_type_id: _builtins.str = ...,
        fecha_inicio: _builtins.str = ...,
        fecha_fin: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fecha_fin", b"fecha_fin", "fecha_inicio", b"fecha_inicio", "hotel_id", b"hotel_id", "room_type_id", b"room_type_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateReservationRequest: _TypeAlias = CreateReservationRequest  # noqa: Y015

@_typing.final
class CreateReservationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESERVATION_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    MONTO_TOTAL_FIELD_NUMBER: _builtins.int
    reservation_id: _builtins.str
    status: _builtins.str
    monto_total: _builtins.float
    def __init__(
        self,
        *,
        reservation_id: _builtins.str = ...,
        status: _builtins.str = ...,
        monto_total: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["monto_total", b"monto_total", "reservation_id", b"reservation_id", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateReservationResponse: _TypeAlias = CreateReservationResponse  # noqa: Y015

@_typing.final
class GetUserRequest(_message.Message):
    """─ Mensajes Usuarios ─────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserRequest: _TypeAlias = GetUserRequest  # noqa: Y015

@_typing.final
class GetUserResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXISTS_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    exists: _builtins.bool
    name: _builtins.str
    def __init__(
        self,
        *,
        exists: _builtins.bool = ...,
        name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exists", b"exists", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserResponse: _TypeAlias = GetUserResponse  # noqa: Y015

@_typing.final
class UpdateStockRequest(_message.Message):
    """─ Mensajes Inventario ─────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    ROOM_TYPE_ID_FIELD_NUMBER: _builtins.int
    CANTIDAD_FIELD_NUMBER: _builtins.int
    ACCION_FIELD_NUMBER: _builtins.int
    room_type_id: _builtins.str
    cantidad: _builtins.int
    accion: _builtins.str
    """"BLOQUEAR" o "LIBERAR" """
    def __init__(
        self,
        *,
        room_type_id: _builtins.str = ...,
        cantidad: _builtins.int = ...,
        accion: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accion", b"accion", "cantidad", b"cantidad", "room_type_id", b"room_type_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateStockRequest: _TypeAlias = UpdateStockRequest  # noqa: Y015

@_typing.final
class UpdateStockResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateStockResponse: _TypeAlias = UpdateStockResponse  # noqa: Y015

@_typing.final
class SendConfirmationRequest(_message.Message):
    """─ Mensajes Notificaciones ─────────────────────────────────────────────"""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    RESERVATION_ID_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    reservation_id: _builtins.str
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        reservation_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reservation_id", b"reservation_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SendConfirmationRequest: _TypeAlias = SendConfirmationRequest  # noqa: Y015

@_typing.final
class SendConfirmationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SendConfirmationResponse: _TypeAlias = SendConfirmationResponse  # noqa: Y015
