# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/notifications.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/notifications.proto\x12\x02pb\"_\n\x17SendConfirmationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x0c\n\x04tipo\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"+\n\x18SendConfirmationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x64\n\x13NotificationService\x12M\n\x10SendConfirmation\x12\x1b.pb.SendConfirmationRequest\x1a\x1c.pb.SendConfirmationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDCONFIRMATIONREQUEST']._serialized_start=33
  _globals['_SENDCONFIRMATIONREQUEST']._serialized_end=128
  _globals['_SENDCONFIRMATIONRESPONSE']._serialized_start=130
  _globals['_SENDCONFIRMATIONRESPONSE']._serialized_end=173
  _globals['_NOTIFICATIONSERVICE']._serialized_start=175
  _globals['_NOTIFICATIONSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
