# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x02pb\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"d\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03rol\x18\x04 \x01(\x05\x12\x10\n\x08telefono\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"&\n\x0cUserResponse\x12\x16\n\x04user\x18\x01 \x01(\x0b\x32\x08.pb.User2>\n\x0bUserService\x12/\n\x07GetUser\x12\x12.pb.GetUserRequest\x1a\x10.pb.UserResponseB \n\x11\x63om.sde.user.grpcB\tUserProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.sde.user.grpcB\tUserProtoP\001'
  _globals['_GETUSERREQUEST']._serialized_start=26
  _globals['_GETUSERREQUEST']._serialized_end=54
  _globals['_USER']._serialized_start=56
  _globals['_USER']._serialized_end=156
  _globals['_USERRESPONSE']._serialized_start=158
  _globals['_USERRESPONSE']._serialized_end=196
  _globals['_USERSERVICE']._serialized_start=198
  _globals['_USERSERVICE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
