// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/servicio.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HotelId       string                 `protobuf:"bytes,3,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	RoomTypeId    string                 `protobuf:"bytes,4,opt,name=room_type_id,json=roomTypeId,proto3" json:"room_type_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	FechaInicio   string                 `protobuf:"bytes,6,opt,name=fecha_inicio,json=fechaInicio,proto3" json:"fecha_inicio,omitempty"`
	FechaFin      string                 `protobuf:"bytes,7,opt,name=fecha_fin,json=fechaFin,proto3" json:"fecha_fin,omitempty"`
	MontoTotal    float64                `protobuf:"fixed64,8,opt,name=monto_total,json=montoTotal,proto3" json:"monto_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_pb_servicio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{0}
}

func (x *Reservation) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *Reservation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reservation) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *Reservation) GetRoomTypeId() string {
	if x != nil {
		return x.RoomTypeId
	}
	return ""
}

func (x *Reservation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Reservation) GetFechaInicio() string {
	if x != nil {
		return x.FechaInicio
	}
	return ""
}

func (x *Reservation) GetFechaFin() string {
	if x != nil {
		return x.FechaFin
	}
	return ""
}

func (x *Reservation) GetMontoTotal() float64 {
	if x != nil {
		return x.MontoTotal
	}
	return 0
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_pb_servicio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{1}
}

func (x *GetReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type GetReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationResponse) Reset() {
	*x = GetReservationResponse{}
	mi := &file_pb_servicio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationResponse) ProtoMessage() {}

func (x *GetReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationResponse.ProtoReflect.Descriptor instead.
func (*GetReservationResponse) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{2}
}

func (x *GetReservationResponse) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type ListReservationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsRequest) Reset() {
	*x = ListReservationsRequest{}
	mi := &file_pb_servicio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsRequest) ProtoMessage() {}

func (x *ListReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsRequest.ProtoReflect.Descriptor instead.
func (*ListReservationsRequest) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{3}
}

type ListReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsResponse) Reset() {
	*x = ListReservationsResponse{}
	mi := &file_pb_servicio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsResponse) ProtoMessage() {}

func (x *ListReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsResponse.ProtoReflect.Descriptor instead.
func (*ListReservationsResponse) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{4}
}

func (x *ListReservationsResponse) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HotelId       string                 `protobuf:"bytes,2,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	RoomTypeId    string                 `protobuf:"bytes,3,opt,name=room_type_id,json=roomTypeId,proto3" json:"room_type_id,omitempty"`
	FechaInicio   string                 `protobuf:"bytes,4,opt,name=fecha_inicio,json=fechaInicio,proto3" json:"fecha_inicio,omitempty"`
	FechaFin      string                 `protobuf:"bytes,5,opt,name=fecha_fin,json=fechaFin,proto3" json:"fecha_fin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_pb_servicio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReservationRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *CreateReservationRequest) GetRoomTypeId() string {
	if x != nil {
		return x.RoomTypeId
	}
	return ""
}

func (x *CreateReservationRequest) GetFechaInicio() string {
	if x != nil {
		return x.FechaInicio
	}
	return ""
}

func (x *CreateReservationRequest) GetFechaFin() string {
	if x != nil {
		return x.FechaFin
	}
	return ""
}

type CreateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	MontoTotal    float64                `protobuf:"fixed64,3,opt,name=monto_total,json=montoTotal,proto3" json:"monto_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_pb_servicio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{6}
}

func (x *CreateReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CreateReservationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateReservationResponse) GetMontoTotal() float64 {
	if x != nil {
		return x.MontoTotal
	}
	return 0
}

// ─ Mensajes Usuarios ─────────────────────────────────────────────
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_pb_servicio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Rol           int32                  `protobuf:"varint,4,opt,name=rol,proto3" json:"rol,omitempty"`
	Telefono      string                 `protobuf:"bytes,5,opt,name=telefono,proto3" json:"telefono,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pb_servicio_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*User) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{13}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_pb_servicio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// ─ Mensajes Inventario ─────────────────────────────────────────────
type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomTypeId    string                 `protobuf:"bytes,1,opt,name=room_type_id,json=roomTypeId,proto3" json:"room_type_id,omitempty"`
	Cantidad      int32                  `protobuf:"varint,2,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	Accion        string                 `protobuf:"bytes,3,opt,name=accion,proto3" json:"accion,omitempty"` // "BLOQUEAR" o "LIBERAR"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_pb_servicio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStockRequest) GetRoomTypeId() string {
	if x != nil {
		return x.RoomTypeId
	}
	return ""
}

func (x *UpdateStockRequest) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

func (x *UpdateStockRequest) GetAccion() string {
	if x != nil {
		return x.Accion
	}
	return ""
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_pb_servicio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStockResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// ─ Mensajes Notificaciones ─────────────────────────────────────────────
type SendConfirmationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendConfirmationRequest) Reset() {
	*x = SendConfirmationRequest{}
	mi := &file_pb_servicio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendConfirmationRequest) ProtoMessage() {}

func (x *SendConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendConfirmationRequest.ProtoReflect.Descriptor instead.
func (*SendConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{11}
}

func (x *SendConfirmationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendConfirmationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *SendConfirmationRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

type SendConfirmationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendConfirmationResponse) Reset() {
	*x = SendConfirmationResponse{}
	mi := &file_pb_servicio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendConfirmationResponse) ProtoMessage() {}

func (x *SendConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_servicio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendConfirmationResponse.ProtoReflect.Descriptor instead.
func (*SendConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_pb_servicio_proto_rawDescGZIP(), []int{12}
}

func (x *SendConfirmationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pb_servicio_proto protoreflect.FileDescriptor

const file_pb_servicio_proto_rawDesc = "" +
	"\n" +
	"\x11pb/servicio.proto\x12\x02pb\"\x83\x02\n" +
	"\vReservation\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bhotel_id\x18\x03 \x01(\tR\ahotelId\x12 \n" +
	"\froom_type_id\x18\x04 \x01(\tR\n" +
	"roomTypeId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\ffecha_inicio\x18\x06 \x01(\tR\vfechaInicio\x12\x1b\n" +
	"\tfecha_fin\x18\a \x01(\tR\bfechaFin\x12\x1f\n" +
	"\vmonto_total\x18\b \x01(\x01R\n" +
	"montoTotal\">\n" +
	"\x15GetReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"K\n" +
	"\x16GetReservationResponse\x121\n" +
	"\vreservation\x18\x01 \x01(\v2\x0f.pb.ReservationR\vreservation\"\x19\n" +
	"\x17ListReservationsRequest\"O\n" +
	"\x18ListReservationsResponse\x123\n" +
	"\freservations\x18\x01 \x03(\v2\x0f.pb.ReservationR\freservations\"\xb0\x01\n" +
	"\x18CreateReservationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bhotel_id\x18\x02 \x01(\tR\ahotelId\x12 \n" +
	"\froom_type_id\x18\x03 \x01(\tR\n" +
	"roomTypeId\x12!\n" +
	"\ffecha_inicio\x18\x04 \x01(\tR\vfechaInicio\x12\x1b\n" +
	"\tfecha_fin\x18\x05 \x01(\tR\bfechaFin\"{\n" +
	"\x19CreateReservationResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vmonto_total\x18\x03 \x01(\x01R\n" +
	"montoTotal\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x0fGetUserResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"j\n" +
	"\x12UpdateStockRequest\x12 \n" +
	"\froom_type_id\x18\x01 \x01(\tR\n" +
	"roomTypeId\x12\x1a\n" +
	"\bcantidad\x18\x02 \x01(\x05R\bcantidad\x12\x16\n" +
	"\x06accion\x18\x03 \x01(\tR\x06accion\"/\n" +
	"\x13UpdateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x17SendConfirmationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\"4\n" +
	"\x18SendConfirmationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfe\x01\n" +
	"\x12ReservationService\x12G\n" +
	"\x0eGetReservation\x12\x19.pb.GetReservationRequest\x1a\x1a.pb.GetReservationResponse\x12M\n" +
	"\x10ListReservations\x12\x1b.pb.ListReservationsRequest\x1a\x1c.pb.ListReservationsResponse\x12P\n" +
	"\x11CreateReservation\x12\x1c.pb.CreateReservationRequest\x1a\x1d.pb.CreateReservationResponse2A\n" +
	"\vUserService\x122\n" +
	"\aGetUser\x12\x12.pb.GetUserRequest\x1a\x13.pb.GetUserResponse2R\n" +
	"\x10InventoryService\x12>\n" +
	"\vUpdateStock\x12\x16.pb.UpdateStockRequest\x1a\x17.pb.UpdateStockResponse2d\n" +
	"\x13NotificationService\x12M\n" +
	"\x10SendConfirmation\x12\x1b.pb.SendConfirmationRequest\x1a\x1c.pb.SendConfirmationResponseB'Z%github.com/darkkings19/mi-servicio/pbb\x06proto3"

var (
	file_pb_servicio_proto_rawDescOnce sync.Once
	file_pb_servicio_proto_rawDescData []byte
)

func file_pb_servicio_proto_rawDescGZIP() []byte {
	file_pb_servicio_proto_rawDescOnce.Do(func() {
		file_pb_servicio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_servicio_proto_rawDesc), len(file_pb_servicio_proto_rawDesc)))
	})
	return file_pb_servicio_proto_rawDescData
}

var file_pb_servicio_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pb_servicio_proto_goTypes = []any{
	(*Reservation)(nil),               // 0: pb.Reservation
	(*GetReservationRequest)(nil),     // 1: pb.GetReservationRequest
	(*GetReservationResponse)(nil),    // 2: pb.GetReservationResponse
	(*ListReservationsRequest)(nil),   // 3: pb.ListReservationsRequest
	(*ListReservationsResponse)(nil),  // 4: pb.ListReservationsResponse
	(*CreateReservationRequest)(nil),  // 5: pb.CreateReservationRequest
	(*CreateReservationResponse)(nil), // 6: pb.CreateReservationResponse
	(*GetUserRequest)(nil),            // 7: pb.GetUserRequest
	(*GetUserResponse)(nil),           // 8: pb.GetUserResponse
	(*UpdateStockRequest)(nil),        // 9: pb.UpdateStockRequest
	(*UpdateStockResponse)(nil),       // 10: pb.UpdateStockResponse
	(*SendConfirmationRequest)(nil),   // 11: pb.SendConfirmationRequest
	(*SendConfirmationResponse)(nil),  // 12: pb.SendConfirmationResponse
	(*User)(nil),                     // 13: pb.User
}
var file_pb_servicio_proto_depIdxs = []int32{
	0,  // 0: pb.GetReservationResponse.reservation:type_name -> pb.Reservation
	0,  // 1: pb.ListReservationsResponse.reservations:type_name -> pb.Reservation
	13, // 2: pb.GetUserResponse.user:type_name -> pb.User
	1,  // 3: pb.ReservationService.GetReservation:input_type -> pb.GetReservationRequest
	3,  // 4: pb.ReservationService.ListReservations:input_type -> pb.ListReservationsRequest
	5,  // 5: pb.ReservationService.CreateReservation:input_type -> pb.CreateReservationRequest
	7,  // 6: pb.UserService.GetUser:input_type -> pb.GetUserRequest
	9,  // 7: pb.InventoryService.UpdateStock:input_type -> pb.UpdateStockRequest
	11, // 8: pb.NotificationService.SendConfirmation:input_type -> pb.SendConfirmationRequest
	2,  // 9: pb.ReservationService.GetReservation:output_type -> pb.GetReservationResponse
	4,  // 10: pb.ReservationService.ListReservations:output_type -> pb.ListReservationsResponse
	6,  // 11: pb.ReservationService.CreateReservation:output_type -> pb.CreateReservationResponse
	8,  // 12: pb.UserService.GetUser:output_type -> pb.GetUserResponse
	10, // 13: pb.InventoryService.UpdateStock:output_type -> pb.UpdateStockResponse
	12, // 14: pb.NotificationService.SendConfirmation:output_type -> pb.SendConfirmationResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_servicio_proto_init() }
func file_pb_servicio_proto_init() {
	if File_pb_servicio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_servicio_proto_rawDesc), len(file_pb_servicio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_pb_servicio_proto_goTypes,
		DependencyIndexes: file_pb_servicio_proto_depIdxs,
		MessageInfos:      file_pb_servicio_proto_msgTypes,
	}.Build()
	File_pb_servicio_proto = out.File
	file_pb_servicio_proto_goTypes = nil
	file_pb_servicio_proto_depIdxs = nil
}
